version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  backend:
    build: ./back/BackEnd/
    container_name: backend
    networks:
      - dockerapi-dev
    restart: always
    ports:
      - "5001:80"
  client:
    container_name: client
    build:
      context: ./web_client
      dockerfile: Dockerfile
    stdin_open: true
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - dockerapi-dev